// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQgPZ_FspLVrBfUqNd5Cqcrn6i17OCFA',
    appId: '1:225336364489:android:ff7333d0b6d63ab066ec18',
    messagingSenderId: '225336364489',
    projectId: 'loginfeature-a354a',
    databaseURL:
        'https://loginfeature-a354a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'loginfeature-a354a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOtc29zkGpbrVfkOUuJqA_WqT6NY1fec',
    appId: '1:225336364489:ios:f830b6ec48784b0866ec18',
    messagingSenderId: '225336364489',
    projectId: 'loginfeature-a354a',
    databaseURL:
        'https://loginfeature-a354a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'loginfeature-a354a.firebasestorage.app',
    iosClientId:
        '225336364489-kj3sud4l7u8604g4saer8qqm23gsnfhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFeature',
  );
}
